services:
  node_server:
    build: .
    container_name: node_server
    restart: always
    # env_file:
    #   - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: 3000
      BINANCE_API_SECRET: ${BINANCE_API_SECRET}
      BINANCE_API_KEY: ${BINANCE_API_KEY}
    ports:
      - "5007:3000"
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    command: ["node", "index.js"]